# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 294)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 471, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label.setObjectName("label")
        self.url = QtWidgets.QLineEdit(self.frame)
        self.url.setGeometry(QtCore.QRect(50, 10, 291, 21))
        self.url.setObjectName("url")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 41, 21))
        self.label_2.setObjectName("label_2")
        self.pwd = QtWidgets.QLineEdit(self.frame)
        self.pwd.setGeometry(QtCore.QRect(390, 10, 61, 21))
        self.pwd.setObjectName("pwd")
        self.dbconf = QtWidgets.QTextEdit(self.frame)
        self.dbconf.setGeometry(QtCore.QRect(50, 40, 401, 161))
        self.dbconf.setObjectName("dbconf")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.edt_tag = QtWidgets.QLineEdit(self.frame)
        self.edt_tag.setGeometry(QtCore.QRect(50, 210, 401, 20))
        self.edt_tag.setObjectName("edt_tag")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 31, 21))
        self.label_4.setObjectName("label_4")
        self.cbo_category = QtWidgets.QComboBox(self.frame)
        self.cbo_category.setGeometry(QtCore.QRect(50, 240, 111, 22))
        self.cbo_category.setObjectName("cbo_category")
        self.cbo_category.addItem("")
        self.cbo_category.addItem("")
        self.cbo_category.addItem("")
        self.cbo_category.addItem("")
        self.cbo_shelltype = QtWidgets.QComboBox(self.frame)
        self.cbo_shelltype.setGeometry(QtCore.QRect(170, 240, 101, 22))
        self.cbo_shelltype.setObjectName("cbo_shelltype")
        self.cbo_shelltype.addItem("")
        self.cbo_shelltype.addItem("")
        self.cbo_shelltype.addItem("")
        self.cbo_shelltype.addItem("")
        self.cbo_shelltype.addItem("")
        self.cbo_encoding = QtWidgets.QComboBox(self.frame)
        self.cbo_encoding.setGeometry(QtCore.QRect(280, 240, 101, 22))
        self.cbo_encoding.setObjectName("cbo_encoding")
        self.cbo_encoding.addItem("")
        self.cbo_encoding.addItem("")
        self.cbo_encoding.addItem("")
        self.cbo_encoding.addItem("")
        self.cbo_encoding.addItem("")
        self.cbo_encoding.addItem("")
        self.btnAdd = QtWidgets.QPushButton(self.frame)
        self.btnAdd.setGeometry(QtCore.QRect(390, 240, 61, 23))
        self.btnAdd.setObjectName("btnAdd")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加"))
        self.label.setText(_translate("Dialog", "Shell："))
        self.label_2.setText(_translate("Dialog", "Pass:"))
        self.label_3.setText(_translate("Dialog", "Conf："))
        self.label_4.setText(_translate("Dialog", "Mark:"))
        self.cbo_category.setItemText(0, _translate("Dialog", "SiteGroup"))
        self.cbo_category.setItemText(1, _translate("Dialog", "Default"))
        self.cbo_category.setItemText(2, _translate("Dialog", "Group1"))
        self.cbo_category.setItemText(3, _translate("Dialog", "Add..."))
        self.cbo_shelltype.setItemText(0, _translate("Dialog", "ShellType"))
        self.cbo_shelltype.setItemText(1, _translate("Dialog", "ASP"))
        self.cbo_shelltype.setItemText(2, _translate("Dialog", "ASPX"))
        self.cbo_shelltype.setItemText(3, _translate("Dialog", "PHP"))
        self.cbo_shelltype.setItemText(4, _translate("Dialog", "Custom"))
        self.cbo_encoding.setItemText(0, _translate("Dialog", "Encoding"))
        self.cbo_encoding.setItemText(1, _translate("Dialog", "UTF-8"))
        self.cbo_encoding.setItemText(2, _translate("Dialog", "GBK"))
        self.cbo_encoding.setItemText(3, _translate("Dialog", "Euc-KR"))
        self.cbo_encoding.setItemText(4, _translate("Dialog", "Euc-JP"))
        self.cbo_encoding.setItemText(5, _translate("Dialog", "ISO-8859-1"))
        self.btnAdd.setText(_translate("Dialog", "ADD"))

