# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1043, 618)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconPath = QtWidgets.QWidget(Form)
        self.iconPath.setObjectName("iconPath")
        self.horizontalLayout.addWidget(self.iconPath)
        self.comboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMidLineWidth(2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.leftView = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftView.sizePolicy().hasHeightForWidth())
        self.leftView.setSizePolicy(sizePolicy)
        self.leftView.setMinimumSize(QtCore.QSize(100, 0))
        self.leftView.setMouseTracking(True)
        self.leftView.setTabletTracking(True)
        self.leftView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.leftView.setIconSize(QtCore.QSize(16, 16))
        self.leftView.setColumnCount(1)
        self.leftView.setObjectName("leftView")
        item_0 = QtWidgets.QTreeWidgetItem(self.leftView)
        self.leftView.header().setVisible(False)
        self.rightView = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightView.sizePolicy().hasHeightForWidth())
        self.rightView.setSizePolicy(sizePolicy)
        self.rightView.setMinimumSize(QtCore.QSize(200, 0))
        self.rightView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.rightView.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.rightView.setIconSize(QtCore.QSize(16, 16))
        self.rightView.setObjectName("rightView")
        item_0 = QtWidgets.QTreeWidgetItem(self.rightView)
        self.verticalLayout.addWidget(self.splitter)
        self.action_fileAdd = QtWidgets.QAction(Form)
        self.action_fileAdd.setObjectName("action_fileAdd")
        self.action_folderAdd = QtWidgets.QAction(Form)
        self.action_folderAdd.setObjectName("action_folderAdd")
        self.action_upload = QtWidgets.QAction(Form)
        self.action_upload.setObjectName("action_upload")
        self.action_download = QtWidgets.QAction(Form)
        self.action_download.setObjectName("action_download")
        self.action_wget = QtWidgets.QAction(Form)
        self.action_wget.setObjectName("action_wget")
        self.action_edit = QtWidgets.QAction(Form)
        self.action_edit.setObjectName("action_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Go"))
        self.splitter.setToolTip(_translate("Form", "文件管理"))
        self.splitter.setStatusTip(_translate("Form", "文件管理"))
        self.splitter.setWhatsThis(_translate("Form", "文件管理"))
        self.leftView.headerItem().setText(0, _translate("Form", "Folder"))
        __sortingEnabled = self.leftView.isSortingEnabled()
        self.leftView.setSortingEnabled(False)
        self.leftView.topLevelItem(0).setText(0, _translate("Form", "/"))
        self.leftView.setSortingEnabled(__sortingEnabled)
        self.rightView.headerItem().setText(0, _translate("Form", "Name"))
        self.rightView.headerItem().setText(1, _translate("Form", "Time"))
        self.rightView.headerItem().setText(2, _translate("Form", "Size"))
        self.rightView.headerItem().setText(3, _translate("Form", "Attribute"))
        __sortingEnabled = self.rightView.isSortingEnabled()
        self.rightView.setSortingEnabled(False)
        self.rightView.topLevelItem(0).setText(0, _translate("Form", "etc"))
        self.rightView.topLevelItem(0).setText(1, _translate("Form", "2018.09.12"))
        self.rightView.topLevelItem(0).setText(2, _translate("Form", "10K"))
        self.rightView.topLevelItem(0).setText(3, _translate("Form", "777"))
        self.rightView.setSortingEnabled(__sortingEnabled)
        self.action_fileAdd.setText(_translate("Form", "新建文件"))
        self.action_fileAdd.setToolTip(_translate("Form", "新建文件"))
        self.action_fileAdd.setShortcut(_translate("Form", "Ctrl+N"))
        self.action_folderAdd.setText(_translate("Form", "新建文件夹"))
        self.action_folderAdd.setToolTip(_translate("Form", "新建文件夹"))
        self.action_folderAdd.setShortcut(_translate("Form", "Ctrl+Shift+N"))
        self.action_upload.setText(_translate("Form", "上传"))
        self.action_upload.setToolTip(_translate("Form", "上传"))
        self.action_upload.setShortcut(_translate("Form", "Ctrl+U"))
        self.action_download.setText(_translate("Form", "下载"))
        self.action_download.setToolTip(_translate("Form", "下载"))
        self.action_download.setShortcut(_translate("Form", "Ctrl+D"))
        self.action_wget.setText(_translate("Form", "wget"))
        self.action_wget.setToolTip(_translate("Form", "wget"))
        self.action_wget.setShortcut(_translate("Form", "Ctrl+W"))
        self.action_edit.setText(_translate("Form", "编辑"))
        self.action_edit.setToolTip(_translate("Form", "编辑"))
        self.action_edit.setShortcut(_translate("Form", "Ctrl+E"))

import mudao.resource_rc
